# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea2111ea827382abad17102dce8e276a077f0bc68b9488bd0f18783e80620ea937a28b00f3cf221a881d643efd05394de6a54af5229824fd391f4bc48cdf913c

test:
  secret_key_base: 6a939a5ef721271196060eadf1b2dda1950c498e34add11cf261ed593758db1cf97f6fe893fe3c064190382a447e9b4f517b704124d05a14a51770ed8a93c084

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
